---
- name: Deploy Evaluate-STIG to ProgramData
  hosts: all
  gather_facts: no

  vars:
    src_share: "\\\\192.168.40.42\\raw-images\\Evaluate-STIG"
    dest_root: "C:\\ProgramData"
    dest_path: "{{ dest_root }}\\Evaluate-STIG"
    timestamp: "{{ lookup('pipe', 'powershell -Command Get-Date -Format yyyyMMdd_HHmmss') }}"
    robolog: "C:\\Windows\\Temp\\robocopy_Evaluate-STIG_{{ timestamp }}.log"

  tasks:
    - name: Ensure destination root exists
      ansible.windows.win_file:
        path: "{{ dest_root }}"
        state: directory

    - name: (Optional) Add SMB creds for the source share
      ansible.windows.win_command: >
        cmdkey /add:192.168.40.42 /user:{{ smb_user }} /pass:{{ smb_pass }}
      when: smb_user | default('') | length > 0
      changed_when: false

    - name: Copy Evaluate-STIG with RoboCopy
      ansible.windows.win_shell: |
        robocopy "{{ src_share }}" "{{ dest_path }}" /E /COPY:DAT /DCOPY:DAT /R:2 /W:5 /MT:8 /NFL /NDL /NP /LOG:"{{ robolog }}"
      args:
        executable: cmd
      register: robocopy_result

    - name: Display Robocopy summary
      ansible.builtin.debug:
        var: robocopy_result.stdout

    - name: Verify Evaluate-STIG copied successfully
      ansible.windows.win_stat:
        path: "{{ dest_path }}"
      register: stig_check

    - name: Display confirmation
      ansible.builtin.debug:
        msg: "✅ Evaluate-STIG successfully copied to {{ dest_path }}"
      when: stig_check.stat.exists

    - name: (Optional) Remove temp SMB creds
      ansible.windows.win_command: cmdkey /delete:192.168.40.42
      when: smb_user | default('') | length > 0
      changed_when: false
