---
- name: Deploy Evaluate-STIG to ProgramData
  hosts: all
  gather_facts: no

  vars:
    src_share: "\\\\192.168.40.42\\raw-images\\Evaluate-STIG"
    dest_path: "C:\\ProgramData\\Evaluate-STIG"
    smb_user: "{{ smb_user }}"
    smb_pass: "{{ smb_pass }}"

  tasks:
    - name: Ensure destination path exists
      ansible.windows.win_file:
        path: "{{ dest_path }}"
        state: directory

    - name: Copy Evaluate-STIG using PowerShell Copy-Item
      ansible.windows.win_powershell:
        script: |
          $Source = "{{ src_share }}"
          $Destination = "{{ dest_path }}"
          $Username = "{{ smb_user }}"
          $Password = "{{ smb_pass }}" | ConvertTo-SecureString -AsPlainText -Force
          $Cred = New-Object System.Management.Automation.PSCredential($Username, $Password)

          # Map temporary drive to access the share
          New-PSDrive -Name "Z" -PSProvider FileSystem -Root $Source -Credential $Cred -ErrorAction Stop | Out-Null

          # Perform copy
          Copy-Item -Path "Z:\*" -Destination $Destination -Recurse -Force -ErrorAction Stop

          # Remove temporary mapping
          Remove-PSDrive -Name "Z" -Force -ErrorAction SilentlyContinue
      register: copy_result
      ignore_errors: false

    - name: Display copy result
      ansible.builtin.debug:
        var: copy_result
